// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9DL6GqdeRF7XevWV-5EFBA9TDcol8_1o',
    appId: '1:174594141959:web:a8d57bf9bcde388c1edfa2',
    messagingSenderId: '174594141959',
    projectId: 'gymnow-e1ebd',
    authDomain: 'gymnow-e1ebd.firebaseapp.com',
    storageBucket: 'gymnow-e1ebd.firebasestorage.app',
    measurementId: 'G-F59FNY7TNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeJ_RjjKs9WUrBd8WnPKev9jvpej0QuAM',
    appId: '1:174594141959:android:8e7ae64e73c75a971edfa2',
    messagingSenderId: '174594141959',
    projectId: 'gymnow-e1ebd',
    storageBucket: 'gymnow-e1ebd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGC_xrMBvwSCKEQD5vjwUj2YyL3fjbPa8',
    appId: '1:174594141959:ios:9cfecd8d042e1a8c1edfa2',
    messagingSenderId: '174594141959',
    projectId: 'gymnow-e1ebd',
    storageBucket: 'gymnow-e1ebd.firebasestorage.app',
    iosBundleId: 'com.example.gymNow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGC_xrMBvwSCKEQD5vjwUj2YyL3fjbPa8',
    appId: '1:174594141959:ios:9cfecd8d042e1a8c1edfa2',
    messagingSenderId: '174594141959',
    projectId: 'gymnow-e1ebd',
    storageBucket: 'gymnow-e1ebd.firebasestorage.app',
    iosBundleId: 'com.example.gymNow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9DL6GqdeRF7XevWV-5EFBA9TDcol8_1o',
    appId: '1:174594141959:web:31cc080a2c396fe41edfa2',
    messagingSenderId: '174594141959',
    projectId: 'gymnow-e1ebd',
    authDomain: 'gymnow-e1ebd.firebaseapp.com',
    storageBucket: 'gymnow-e1ebd.firebasestorage.app',
    measurementId: 'G-HMB0PSMMG4',
  );
}
